// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKQVZnFj5Sbfz5F7dEjGZFo_SCHeC8fBM',
    appId: '1:508670404684:web:fd82a9894eda500931ece9',
    messagingSenderId: '508670404684',
    projectId: 'dimareinic',
    authDomain: 'dimareinic.firebaseapp.com',
    storageBucket: 'dimareinic.appspot.com',
    measurementId: 'G-1KLX4VWBTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7JZRAgcWOhgMVX7mkQ5HfgnBld57e2MA',
    appId: '1:508670404684:android:78c65d18e97f3bd931ece9',
    messagingSenderId: '508670404684',
    projectId: 'dimareinic',
    storageBucket: 'dimareinic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAYSURchyWg0vB28vu70M4IWnfDc_kRhg',
    appId: '1:508670404684:ios:1ab25038b361d35a31ece9',
    messagingSenderId: '508670404684',
    projectId: 'dimareinic',
    storageBucket: 'dimareinic.appspot.com',
    iosClientId: '508670404684-e64amf7524e22ch14o2jnplm30mcl7on.apps.googleusercontent.com',
    iosBundleId: 'com.example.projTest',
  );
}
